### ISSUE TITLE
Duplicate icons/artifacts on Win11 taskbar

### ISSUE THREAD

**Issue by kegobass** [Jax-Core/ModularPlayers#15]
After installing Jaxcore/ModularPlayers, 2.4.2 I am seeing leftover icon artifacts in the Win11 taskbar.  If I hover of them, they temporarily disappear but return again.  If I uninstall Rainmeter, Jaxcore, ModularPlayer, etc,, the issue no longer occurs.  

![Screenshot_1](https://user-images.githubusercontent.com/59669068/163716759-075a3464-6dde-443e-aa53-d68985520b88.png)

**Comment by EnhancedJax** [comment]
This is not an issue regarding modular players. Check if these artifacts are caused by the application they represent

**Comment by kegobass** [comment]
It seems odd the issue just started yesterday when I installed ModularPlayers and I do not not have the issue if I uninstall Rainmeter/JaxCore/Modular Players.  The issue happens on all apps on the taskbar, not just one.

Update:  It appears to be with Jaxcore, not ModularPlayers.  If I don't load Jaxcore, no artifacts.

**Comment by kegobass** [comment]
I reloaded everything and the issue appears to be gone.  Not sure what happened initially.

**Comment by EnhancedJax** [comment]
Odd... I'll keep my eyes on this
