### ISSUE TITLE
Trying to get progress bar to work on music player "blur"

### ISSUE THREAD

**Issue by Efikun** [Jax-Core/ModularPlayers#2]
Hello
I love the blur music player, I've been trying to get it to have a progress bar as well since that's quite useful. So far I managed to get a progress bar on it, visible, and when you click on it, it does move to the right point in the song. The only issue is that it doesn't seem to progress. The startcap doesn't move at all, I'm not sure why. 
I didn't really know what I was doing honestly, but I copied the [ProgBar] from the MIUI player, which seemed to get it to function as a progress bar but the progress cap doesn't move. I'd really appreciate it if you could help me!
Also one more thing, less important but still useful. Is there an option to have the music player draggable? I tried enabling it on rainmeter but I couldn't find this exact player in active skins, and the modularplayer skin is draggable so I'm not sure how to get the actual player to be draggable. That would very useful.
Thank you so much!

**Comment by EnhancedJax** [comment]
Hey. Try holding Ctrl shift when dragging. What happens when you try to drag it without holding down is controlling the music. Swipe left or right to cycle through the songs. For the progbar set the control variable to 1.

**Comment by Efikun** [comment]
Thank you! ^^ I changed the Prog and control variables to 1 and it worked ^^ 
Your interface is the most beautiful I've seen, thank you so much for sharing it!

**Comment by Efikun** [comment]
So, now there seems to be a new problem o.o I'm not sure why, the display of the progress bar isn't syncing well with the music, so it doesn't slide with the music. The first 2 or 3 seconds into playing it moves according to the music, and then it stops moving for a good third of the song, and it "jumps" after a while to the correct place, but doesn't smoothly move with the music. This happens with all of the players that have a progress bar, not just "blur". I'm not sure how to fix that, do you know what it might be? I can attach files if needed.
Thanks!

**Comment by EnhancedJax** [comment]
I don't think that is a problem that I can fix quickly, sorry. I'll try to look for a solution though, but this has never happened to me before.

**Comment by Efikun** [comment]
I'm not sure what the problem might be since I deleted the skin files and then the entire module and reinstalled the .rmskin but that didn't work. This happens with all music players, and on those that show current time, it's even clearer. When a new song would start, or i'd change a music player or refresh the skin, you can see the current time of the song move from 00:00 to about 00:02 or 3 and then stop. after a while it would catch up, every time it's different, sometimes it would jump to 00:18 and others to 00:41 or other times. It would keep getting stuck and then catching up after a long time and happen again in the next song.
Ig it has something to do with the ability to keep retrieving the time of the song, because it works after a refresh for a few seconds and stops.
I'm not sure how to fix that because I don't actually know how to write this sort of code myself ><
If that's complicated it's ok because it's not so bad since technically it works and skips accordingly when pressing the progress bar. Just wondering what it is.
Thanks!

**Comment by Efikun** [comment]
It was magically solved today after I turned the pc on. I'm just happy everything looks exactly as I wanted :D Thanks so much for your help! ^^ now everything looks great :D
![My Desktop](https://user-images.githubusercontent.com/89855151/132005893-c7b2463d-dcbc-4099-a14b-6fa36f27e3fd.png)

**Comment by Mnfinity** [comment]
pls bro i don't no why but the blur effect doesn't work
