### ISSUE TITLE
Invalid Player Type Error

### ISSUE THREAD

**Issue by barbarosselimbuyukelci** [Jax-Core/ModularPlayers#26]
Here im adding 2 screenshots;

![resim](https://user-images.githubusercontent.com/17678347/206931027-8003aa1d-6e8b-4f99-8690-2b5fc07b23c9.png)

![resim](https://user-images.githubusercontent.com/17678347/206931039-00018406-161d-40eb-a0c1-7aae2c0826ed.png)

How can I solve this?

**Comment by EnhancedJax** [comment]
Try using auto method for the media player. Guide here: https://wiki.jaxcore.app/getting-started/faqs/media-player-faqs#auto-method
