### ISSUE TITLE
Doesn't works with iTunes

### ISSUE THREAD

**Issue by firminunderscore** [Jax-Core/ModularPlayers#6]
Hello 👋
The skin doesn't works with iTunes 

![image](https://user-images.githubusercontent.com/40271484/137583337-44da64ff-8f0e-4fce-80a4-5562435e1a6b.png)

**Comment by EnhancedJax** [comment]
Are you using the latest version of iTunes with the player selected for the music player?

**Comment by firminunderscore** [comment]
I didn't change anything and it's working 🤔
I think it only a bug

BUT, it not fully working LOL
![image](https://user-images.githubusercontent.com/40271484/137583677-5eb5c0f7-4a20-40a6-b8f0-58a424a6c834.png)

**Comment by EnhancedJax** [comment]
Seems working for me

**Comment by firminunderscore** [comment]
It works also for me. However, it works not entirely... It not display always my music (with iTunes) and it does not always display the good music (with iTunes/AIMP) 🤔
I don't see what could cause this

**Comment by EnhancedJax** [comment]
I'll try it tomorrow and take a look...
